services:
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    depends_on:
      - app
    links:
      - app
    ports:
      - "80:80"
  
  app:
    build: ./flask
    container_name: "app"
    expose:
      - 8080
    env_file: .env
    environment:
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URI}
      - FLASK_ENV=production
      - FLASK_APP=/app/main.py
    depends_on:
      - db
    restart: always
    volumes:
      - "./flask:/app"
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: atividade_db
    volumes:
      - ./db:/var/lib/mysql
    restart: always