version: "3"
services:
  db:
    image: mysql:latest
    container_name: mariadb_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=frameworks_db
    volumes:
      - ./db:/var/lib/mysql
